//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMPlanHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRMPlanHead()
        {
            this.CRMPlanList = new HashSet<CRMPlanList>();
        }
    
        public long ID { get; set; }
        public string CRMApplyNo { get; set; }
        public string ClientNo { get; set; }
        public string ClientName { get; set; }
        public string ApplicantId { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantPhone { get; set; }
        public string ApplicantDept { get; set; }
        public string ApplicantJob { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string SaleGroup { get; set; }
        public string OrderSource { get; set; }
        public byte[] Photo { get; set; }
        public string Remark { get; set; }
        public string Reserve1 { get; set; }
        public string Reserve2 { get; set; }
        public string Reserve3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMPlanList> CRMPlanList { get; set; }
    }
}
