//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaHuoPlan
    {
        public int ID { get; set; }
        public string danjutype { get; set; }
        public string danjuno { get; set; }
        public string itemno { get; set; }
        public string itemname { get; set; }
        public string spec { get; set; }
        public string saleunit { get; set; }
        public Nullable<decimal> salequt { get; set; }
        public Nullable<decimal> outqut { get; set; }
        public Nullable<decimal> boxnum { get; set; }
        public Nullable<System.DateTime> fhdate { get; set; }
    }
}
