//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInfo
    {
        public int ID { get; set; }
        public string ItemNo { get; set; }
        public string CRMID { get; set; }
        public string ItemName { get; set; }
        public string Spec { get; set; }
        public string MainUtil { get; set; }
        public string SlaveUtil { get; set; }
        public decimal ConvertRate { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModTime_CRM { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string InName { get; set; }
        public string MaterialItem { get; set; }
        public string Workshops { get; set; }
        public string ModUser_APS { get; set; }
        public Nullable<System.DateTime> ModTime_APS { get; set; }
    }
}
