//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NanXingGuoRen_WMSEntities4 : DbContext
    {
        public NanXingGuoRen_WMSEntities4()
            : base("name=NanXingGuoRen_WMSEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGVAlarmLog> AGVAlarmLog { get; set; }
        public virtual DbSet<AGVMissionInfo> AGVMissionInfo { get; set; }
        public virtual DbSet<AGVMissionInfo_Floor> AGVMissionInfo_Floor { get; set; }
        public virtual DbSet<Configs> Configs { get; set; }
        public virtual DbSet<CRMFiles> CRMFiles { get; set; }
        public virtual DbSet<CRMPlanHead> CRMPlanHead { get; set; }
        public virtual DbSet<CRMPlanList> CRMPlanList { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<Depts> Depts { get; set; }
        public virtual DbSet<DeviceStatesInfo> DeviceStatesInfo { get; set; }
        public virtual DbSet<FaHuoPlan> FaHuoPlan { get; set; }
        public virtual DbSet<ItemInfo> ItemInfo { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<Onlines> Onlines { get; set; }
        public virtual DbSet<PrdMissionSL> PrdMissionSL { get; set; }
        public virtual DbSet<ProcessClasses> ProcessClasses { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<Productiondt> Productiondt { get; set; }
        public virtual DbSet<ProductOrderheaders> ProductOrderheaders { get; set; }
        public virtual DbSet<ProductOrderlists> ProductOrderlists { get; set; }
        public virtual DbSet<RolePowers> RolePowers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SensorData> SensorData { get; set; }
        public virtual DbSet<SERIALNO> SERIALNO { get; set; }
        public virtual DbSet<STAFF> STAFF { get; set; }
        public virtual DbSet<StockPlan> StockPlan { get; set; }
        public virtual DbSet<SYSPARM> SYSPARM { get; set; }
        public virtual DbSet<TelenClients> TelenClients { get; set; }
        public virtual DbSet<TiShengJiState> TiShengJiState { get; set; }
        public virtual DbSet<Titles> Titles { get; set; }
        public virtual DbSet<TouLiaoRecord> TouLiaoRecord { get; set; }
        public virtual DbSet<TrayPro> TrayPro { get; set; }
        public virtual DbSet<TrayState> TrayState { get; set; }
        public virtual DbSet<UpdateApp> UpdateApp { get; set; }
        public virtual DbSet<UpdateFiles> UpdateFiles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WareArea> WareArea { get; set; }
        public virtual DbSet<WareAreaClass> WareAreaClass { get; set; }
        public virtual DbSet<WareHouse> WareHouse { get; set; }
        public virtual DbSet<WareLocation> WareLocation { get; set; }
        public virtual DbSet<WorkShopProcesses> WorkShopProcesses { get; set; }
    }
}
