//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrdMissionSL
    {
        public int SN { get; set; }
        public string PrdMissionNo { get; set; }
        public System.DateTime PRODate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string WORKGRP { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string Spec { get; set; }
        public string QCStandard { get; set; }
        public string Client { get; set; }
        public string ORDERNO { get; set; }
        public string CHECKMAN { get; set; }
        public string PackMan { get; set; }
        public string COLOR { get; set; }
        public string LOTNO { get; set; }
        public string GRADE { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Thickness { get; set; }
        public string CASENO { get; set; }
        public string LabelName { get; set; }
        public string BoxLblName { get; set; }
        public Nullable<short> WlStatus { get; set; }
        public Nullable<short> IsReturn { get; set; }
        public Nullable<short> IsPrint { get; set; }
        public string Password { get; set; }
        public Nullable<short> IsCancel { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string KaiDan { get; set; }
        public Nullable<System.DateTime> KaiDanDate { get; set; }
        public string Auditer { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string PiZhun { get; set; }
        public Nullable<System.DateTime> PiZhunDate { get; set; }
        public string REMARK { get; set; }
        public string RESERVE1 { get; set; }
        public string RESERVE2 { get; set; }
        public string RESERVE3 { get; set; }
        public string RESERVE4 { get; set; }
        public string RESERVE5 { get; set; }
        public string RESERVE6 { get; set; }
        public string RESERVE7 { get; set; }
        public string RESERVE8 { get; set; }
        public string RESERVE9 { get; set; }
        public string RESERVE10 { get; set; }
        public string RESERVE11 { get; set; }
        public string RESERVE12 { get; set; }
        public string RESERVE13 { get; set; }
        public string RESERVE14 { get; set; }
        public string RESERVE15 { get; set; }
        public string RESERVE16 { get; set; }
        public string RESERVE17 { get; set; }
        public string RESERVE18 { get; set; }
        public string RESERVE19 { get; set; }
        public string RESERVE20 { get; set; }
        public string RESERVE21 { get; set; }
        public string RESERVE22 { get; set; }
        public string RESERVE23 { get; set; }
        public string RESERVE24 { get; set; }
        public string RESERVE25 { get; set; }
        public string RESERVE26 { get; set; }
        public string RESERVE27 { get; set; }
        public string RESERVE28 { get; set; }
        public string RESERVE29 { get; set; }
        public string RESERVE30 { get; set; }
    }
}
