//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessClasses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessClasses()
        {
            this.WorkShopProcesses = new HashSet<WorkShopProcesses>();
        }
    
        public int ID { get; set; }
        public string ProcessClassName { get; set; }
        public int ProcessSort { get; set; }
        public string ProcessReamrk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkShopProcesses> WorkShopProcesses { get; set; }
    }
}
