//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderlists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOrderlists()
        {
            this.Production = new HashSet<Production>();
        }
    
        public int ID { get; set; }
        public string ProductOrder_XuHao { get; set; }
        public string Itemno { get; set; }
        public string ItemName { get; set; }
        public string InName { get; set; }
        public string MaterialItem { get; set; }
        public string Spec { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Class { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> PcCount { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public string Jingbanren { get; set; }
        public string Remark { get; set; }
        public string Clientname { get; set; }
        public Nullable<int> ProductOrderheader_ID { get; set; }
        public string BatchNo { get; set; }
        public string BoxNo { get; set; }
        public string BoxName { get; set; }
        public string Ingredients { get; set; }
        public string Chejianclass { get; set; }
        public string ERPOrderNo { get; set; }
        public string ProductOrder_State { get; set; }
        public Nullable<System.DateTime> Newdate { get; set; }
        public Nullable<System.DateTime> Moddate { get; set; }
        public string Biaozhun { get; set; }
        public string BoxRemark { get; set; }
        public string GiveDept { get; set; }
        public string ProductRecipe { get; set; }
        public Nullable<long> CRMPlanList_ID { get; set; }
    
        public virtual CRMPlanList CRMPlanList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production> Production { get; set; }
        public virtual ProductOrderheaders ProductOrderheaders { get; set; }
    }
}
