//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderheaders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOrderheaders()
        {
            this.ProductOrderlists = new HashSet<ProductOrderlists>();
        }
    
        public int ID { get; set; }
        public string ProductOrderNo { get; set; }
        public Nullable<System.DateTime> Optdate { get; set; }
        public string PositionClass { get; set; }
        public string Remark { get; set; }
        public string orderNo { get; set; }
        public string mergeCells { get; set; }
        public string mergeCellsValue { get; set; }
        public Nullable<System.DateTime> Newdate { get; set; }
        public Nullable<System.DateTime> Moddate { get; set; }
        public string Workshops { get; set; }
        public string WorkshopsValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderlists> ProductOrderlists { get; set; }
    }
}
