//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productiondt
    {
        public int SerialNo { get; set; }
        public string ProSn { get; set; }
        public System.DateTime PRODate { get; set; }
        public string WORKGRP { get; set; }
        public string PrdMissionNo { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string Spec { get; set; }
        public string QCStandard { get; set; }
        public string Client { get; set; }
        public string ORDERNO { get; set; }
        public string CHECKMAN { get; set; }
        public string PackMan { get; set; }
        public string COLOR { get; set; }
        public string LOTNO { get; set; }
        public string GRADE { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string CASENO { get; set; }
        public Nullable<short> WlStatus { get; set; }
        public Nullable<short> IsReturn { get; set; }
        public Nullable<short> IsPrint { get; set; }
        public string Password { get; set; }
        public Nullable<short> IsCancel { get; set; }
        public string OPERATOR { get; set; }
        public string REMARK { get; set; }
        public string RESERVE1 { get; set; }
        public string RESERVE2 { get; set; }
        public string RESERVE3 { get; set; }
        public string RESERVE4 { get; set; }
        public string RESERVE5 { get; set; }
        public string RESERVE6 { get; set; }
        public string RESERVE7 { get; set; }
        public string RESERVE8 { get; set; }
        public string RESERVE9 { get; set; }
        public string RESERVE10 { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<int> PrdDtlSn { get; set; }
    }
}
