//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorData
    {
        public int ID { get; set; }
        public string Floor { get; set; }
        public Nullable<System.DateTime> RefleshTime { get; set; }
        public float Ammeter1 { get; set; }
        public float Ammeter2 { get; set; }
        public float Ammeter3 { get; set; }
        public float Humidity { get; set; }
        public float Temperature { get; set; }
        public float Noise { get; set; }
        public float ToxicGas { get; set; }
        public float StackTemp1 { get; set; }
        public float ChamberTemp1 { get; set; }
        public float StackTemp2 { get; set; }
        public float ChamberTemp2 { get; set; }
        public float StackTemp3 { get; set; }
        public float ChamberTemp3 { get; set; }
        public Nullable<float> DieselOilFlow { get; set; }
    }
}
