//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public string code { get; set; }
        public string name { get; set; }
        public int sex { get; set; }
        public string idcard { get; set; }
        public string address { get; set; }
        public string edured { get; set; }
        public string telephone { get; set; }
        public Nullable<System.DateTime> indate { get; set; }
        public Nullable<System.DateTime> demdate { get; set; }
        public Nullable<int> posstate { get; set; }
        public string department { get; set; }
        public string authorgrp { get; set; }
        public Nullable<decimal> workcls { get; set; }
        public string bank { get; set; }
        public string account { get; set; }
        public Nullable<decimal> timepay { get; set; }
        public Nullable<decimal> basepay { get; set; }
        public string @abstract { get; set; }
        public string password { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT1 { get; set; }
    }
}
