//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiShengJiState
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> InputTime { get; set; }
        public string deviceState { get; set; }
        public string carState { get; set; }
        public string carTarget { get; set; }
        public Nullable<int> CarCount { get; set; }
        public Nullable<int> F1Count { get; set; }
        public Nullable<int> F2Count { get; set; }
        public Nullable<int> F3Count { get; set; }
        public string CarState2 { get; set; }
        public string F1State { get; set; }
        public string F2State { get; set; }
        public string F3State { get; set; }
        public string TsjIp { get; set; }
        public string F1DuiJieWei { get; set; }
        public string F2DuiJieWei { get; set; }
        public string F3DuiJieWei { get; set; }
        public string OrderReceive { get; set; }
    }
}
