//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateApp
    {
        public long ID { get; set; }
        public string App_Name { get; set; }
        public string App_Path { get; set; }
        public string App_Type { get; set; }
        public string App_Version { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string App_NewVersion { get; set; }
        public System.DateTime LastNewTime { get; set; }
    }
}
