//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanXingShouChiJi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShopProcesses
    {
        public int ID { get; set; }
        public string WorkShopName { get; set; }
        public int WorkShopSort { get; set; }
        public int ProcessClass_Id { get; set; }
    
        public virtual ProcessClasses ProcessClasses { get; set; }
    }
}
