// <auto-generated />
namespace NanXingData_WMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Chnage220708_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chnage220708_02));
        
        string IMigrationMetadata.Id
        {
            get { return "202207081153267_Chnage220708_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
