// <auto-generated />
namespace NanXingData_WMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Change220423_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change220423_01));
        
        string IMigrationMetadata.Id
        {
            get { return "202204230645307_Change220423_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
