// <auto-generated />
namespace NanXingData_WMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change220110_21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change220110_21));
        
        string IMigrationMetadata.Id
        {
            get { return "202201101324332_Change220110_21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
