// <auto-generated />
namespace NanXingData_WMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _220110_11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_220110_11));
        
        string IMigrationMetadata.Id
        {
            get { return "202201100403218_220110_11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
